### ISSUE TITLE
AcquireTokenByAuthorizationCodeAsync throw “client info is null” error

### ISSUE THREAD

**Issue by yoelhor** [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi#5]
I'm using AAD B2C **custom** policy based on '[SocialAndLocalAccounts](https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/tree/master/SocialAndLocalAccounts)', setting the AAD applications and encryption keys as mention [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-get-started-custom). While running the application it seems B2C returns valid ID token and authorization code, but when MSAL (1.1.0-preview) executes AcquireTokenByAuthorizationCodeAsync I got following error message, looks like MSAL doesn't able to save the tokens (access and refresh) to local cache.
Message = "client info is null"
ErrorCode = "json_parse_failed"

**Note**: the same policy, with same AAD application still working in the previous version of this demo app. The previous version of this application used MSAL version 1.0.304142221-alpha 

StackTrace = "      at Microsoft.Identity.Client.Internal.ClientInfo.CreateFromJson(String clientInfo)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SaveTokenResponseToCache()
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.PostTokenRequest()
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ConfidentialClientApplication.<AcquireTokenByAuthorizationCodeCommonAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ConfidentialClientApplication.<AcquireTokenByAuthorizationCodeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TaskWebApp.Startup.<OnAuthorizationCodeReceived>d__20.MoveNext() in C:\MyProjects\Microsoft.SDP.Identity\Microsoft.SDP.Identity.DemoWebApp\App_Start\Startup.Auth.cs:line 148

Thank you very much for your assistance in this matter.
Yoel

**Comment by parakhj** [comment]
@yoelhor 

Please update your custom policy...

Add the following line:
`<Item Key="SendTokenResponseBodyWithJsonNumbers">true</Item>`
in your 'JwtIssuer' technical profile (it should be in your base file).

Final result:
 
        <TechnicalProfile Id="JwtIssuer">
          <DisplayName>JWT Issuer</DisplayName>
          <Protocol Name="None" />
          <OutputTokenFormat>JWT</OutputTokenFormat>
          <Metadata>
            <Item Key="client_id">{service:te}</Item>
            <Item Key="issuer_refresh_token_user_identity_claim_type">objectId</Item>

            
            <Item Key="SendTokenResponseBodyWithJsonNumbers">true</Item>
             ...
          </Metadata>

**Comment by gsacavdm** [comment]
Starter pack for custom policies has also been updated. Closing this issue.

**Comment by yoelhor** [comment]
I changed the JWT issuer technical profile with the required metadata you mention, now the values indeed in numeric format (and not string any more) and the demo web app works well. I just wanted to take a moment to sincerely thank you for all of your help and assistance. 

Yoel
